### ISSUE TITLE
gopackagesdriver server error: bind: address already in use

### ISSUE THREAD

**Issue by gonzojive** [stackb/bazel-stack-vscode#113]
This error shows up in the "Starlark Language Server" output:

```
[Info  - 11:57:15 AM] Connection to server got closed. Server will restart.
time="2022-05-28T11:57:16-07:00" level=info msg="Starlark Language server v1.4.8 (2022-05-28)"
time="2022-05-28T11:57:16-07:00" level=info msg="GoPackagesDriver server listening on grpc://localhost:10021" svc=gpd
time="2022-05-28T11:57:16-07:00" level=fatal msg="gopackagesdriver server error: could not create grpc listener: listen tcp 127.0.0.1:10021: bind: address already in use" svc=gpd
```

It might only occur when I have multiple windows open.

It took me a while to realize that the offending code is probably in `bzl`, which I guess is not open source.

**Comment by gonzojive** [comment]
Please let me know if there's any way I can help.

**Comment by akshay-verma** [comment]
I also faced this issue. This started happening with the latest version (v1.9.0), install an older version (v1.8.5) as a workaround.

**Comment by gonzojive** [comment]
Where is the older version available?

**Comment by akshay-verma** [comment]
This is how you can install any version of an extension -
https://i.stack.imgur.com/Yh0jv.gif
