### ISSUE TITLE
Should build the extension file with bazel

### ISSUE THREAD

**Issue by qzmfranklin** [stackb/bazel-stack-vscode#17]
The VSCode extension file is nothing more than a zip file. Should be buildable with a plain `pkg_zip`.

**Comment by pcj** [comment]
I actually tried this and was an interesting learning experience but it's not really worth it.  The `vsce` tool provides a number of validation steps that are useful that would have to be duplicated and maintained.

**Comment by qzmfranklin** [comment]
Urhhh, too bad.
