### ISSUE TITLE
Bazel keymap shortcuts

### ISSUE THREAD

**Issue by UebelAndre** [stackb/bazel-stack-vscode#32]
I may have this wrong but is the default keymap to navigate to the Bazel menu `cmd+shift+Z` (the same as "undo")?

**Comment by pcj** [comment]
@UebelAndre what platform are you on?  If this is indeed the case for your platform, it will need to be changed!

**Comment by UebelAndre** [comment]
I'm on MacOS. This may be a false alarm but I don't recall changing anything when is tarted seeing this behavior (and I'm unsure on how to safely reset to defaults)

**Comment by pcj** [comment]
Oh thanks!  I'll do a bit more research on a good open slot and likely change the keybinding on the next release.

**Comment by pcj** [comment]
Closed by #42 (use shift+command+t)
