### ISSUE TITLE
could not activate feature "bsv.bzl": Error: could not install bzl Error: EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by gorilych** [stackb/bazel-stack-vscode#36]
Looks like error is caused by the fact that `/tmp` and `/home` are on the different devices. Full error message:

```
could not activate feature "bsv.bzl": Error: could not install bzl Error: EXDEV: cross-device link not permitted, rename '/tmp/tmp-23806-Qq804oaUeYgR' -> '/home/me/.vscode-server/data/User/globalStorage/stackbuild.bazel-stack-vscode/bsv.bzl/0.9.2/bzl'
```

**Comment by pcj** [comment]
Thanks @gorilych for this report.

**Comment by purkhusid** [comment]
Hit the same error on my machine

**Comment by pcj** [comment]
Although I was not able to repro this, I added a mv operation that should be compatible with cross device file copy.  If the issue persists, please re-open the issue.  Thanks!
