### ISSUE TITLE
VSCode bzl Download error

### ISSUE THREAD

**Issue by iHuahua** [stackb/bazel-stack-vscode#98]
# VSCode

版本: 1.66.2
提交: dfd34e8260c270da74b5c2d86d61aee4b6d56977
日期: 2022-04-11T07:47:29.396Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

Remote System : CentOS 8.4

# VSCode Plugin
stackbuild.bazel-stack-vscode: v1.8.3

<img width="791" alt="image" src="https://user-images.githubusercontent.com/2878674/163993881-9457b467-e576-469d-9c28-57db1be00248.png">

```
could not install bzl: https://get.bzl.io/linux_amd64/v1.3.19/bzl: The "streams" argument must be specified
```

```
$ wget https://get.bzl.io/linux_amd64/v1.3.19/bzl && chmod +x bzl && ./bzl release
v1.3.16
```
`v1.3.19`/`v1.3.16`Version does not match.

pls help me

**Comment by pcj** [comment]
Should be fixed by #100, please upgrade to version 1.8.4

**Comment by pcj** [comment]
Related to https://github.com/microsoft/vscode-file-downloader/issues/31, https://github.com/microsoft/vscode/issues/144962, https://github.com/nodejs/node/issues/40191

**Comment by pcj** [comment]
There was a packaging issue with 1.8.4, please use 1.8.5 instead.
